### ISSUE TITLE
'unstable' Cargo feature does not exist

### ISSUE THREAD

**Issue by tshepang** [quickwit-oss/bitpacking#37]
Was curious what benchmarks I would get, guided by README...
```
❯ cargo +nightly bench --features unstable
error: Package `bitpacking v0.8.3 (/tmp/bitpacking)` does not have the feature `unstable`
```

Is this the current way:

    cargo +nightly bench

**Comment by fulmicoton** [comment]
Ah yes. Thank you @tshepang ! Actually even nightly is not required anymore.
